title: Njord Soevik # your name (or website title) here
logo: "/images/profilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a mathematics graduate with a passion for data science. Currently a Senior Analyst 2 at CoEnterprise. In my spare time, I like to work on a mix of personal machine learning projects and kaggle competitions. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/njord-soevik-b59a08154/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
