title: Njord Soevik 
logo: "/images/profilePic.png?raw=true" 
description: > 
  I am a Mathematics graduate with a passion for coding and solving complex business problems in big data. I mainly work in Python, as it is an incredibly fun language to work with, and has a great libraries to work with for data science.
  <br><br>
  In my spare time, I love to ski. This year I have taken trips out west and plan to ski the French Alps. 
  <br><br>
  <a href="https://www.linkedin.com/in/njord-soevik-b59a08154/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
