title: Njord Soevik 
logo: "/images/profilePic.png?raw=true" 
description: > 
  I am a Mathematics graduate with a passion for coding and solving complex business problems in big data.
  In my spare time, I love to ski. This year I have taken trips out west and plan to ski the French Alps. 
  <br><br>
  
**Portfolio Overview**
  <br><br>
  ## Machine Learning
  This is where I combine my knowledge from my smaller projects.
  These projects have taught me the most about working with public API's, Python data structures, and dealing cleaning data sets of all formats (JSON, XML, CSV, etc).
  <br><br>
  ## Kaggle
  Kaggle projects are great practice for data cleaning and implementing machine learning. From these I have learned Pyton packages Pandas and Numpy, as well as machine learning packages scikit-learn and Pytorch
  <br><br>
  ## Automation
  These are automation projects I "run into" when working on my machine learning projects. When I find something I can automate in my process, it will get added here.
  
  <br><br>
  <a href="https://www.linkedin.com/in/njord-soevik-b59a08154/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
