title: Njord Soevik 
logo: "/images/profilePic.png?raw=true" 
description: > 
  I am a Mathematics graduate with a passion for coding and solving complex business problems in big data.
  In my spare time, I love to ski. This year I have taken trips out west and plan to ski the French Alps. 
  <br>
  <br>
  This website holds a collection of personal projects in order of subject:<br>
    Data Analysis and Cleaning <br>
    Automation <br>
    Machine Learning <br>
    <br>
    <br>
    
  <a href="/pdf/Njord%20Soevik%20Resume.pdf">View My Resume</a><br>
  <a href="https://www.linkedin.com/in/njord-soevik-b59a08154/">View My LinkedIn Profile</a> 
  

 
theme: jekyll-theme-minimal
google_analytics: UA-163599512-1
