title: Njord Soevik 
logo: "/images/profilePic.png?raw=true" 
description: > 
  I am a Mathematics graduate with a passion for coding and solving complex business problems in big data.
  In my spare time, I love to ski. This year I have taken trips out west and plan to ski the French Alps. 
  <br><br>
  
  #Portfolio Overview
  ##Machine Learning
  This is where I combine my knowledge from my smaller projects, from gathering data, cleaning data, and implementing machine learning to create full scale projects.
  These projects have taught me the most about working with public API's, Python data structures, and dealing cleaning data sets of all formats (JSON / XML / CSV ).
  
  ##Kaggle
  
  API's used: 5
  API's created (Flask): 2
  
  ##Automation
  
  <br><br>
  <a href="https://www.linkedin.com/in/njord-soevik-b59a08154/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
